Repository wuespace/telestion-core, pull requests merged in 2022-03, with the labels that each got.

#531 Update to Gradle 7.4
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: :link: dependencies, :page_facing_up: java

#540 Unit Tests for `MultiMapUtils` and `HeaderInformation`
  modules/telestion-api/src/main/java/de/wuespace/telestion/api/message/HeaderInformation.java
  modules/telestion-api/src/test/java/de/wuespace/telestion/api/message/HeaderInformationTest.java
  modules/telestion-api/src/test/java/de/wuespace/telestion/api/message/JsonMessageTest.java
  modules/telestion-api/src/test/java/de/wuespace/telestion/api/message/MultiMapUtilsTest.java
Labels: :page_facing_up: java, :eyeglasses: tests, :wrench: telestion-api

#552 chore(main): release 0.9.0
  CHANGELOG.md
  version.txt
Labels: autorelease: pending
